### ISSUE TITLE
python-sdk - CI should push to JFrog the tested sdks and client. 

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea#361]
Lets push python SDK and Client to artifactory's PyPI, [see docs](https://www.jfrog.com/confluence/display/JFROG/PyPI+Repositories).

Also, please add a section in the readme describing how to install (pip etc.)

**Comment by shlomi-nx** [comment]
@adolgarev, Is this done? Please link PR and close

**Comment by adolgarev** [comment]
@shlomi-nx not sure this is needed, at the moment one can install from github, see https://github.com/nutanix/papiea-examples/blob/master/example2-python/example/requirements.txt
(instead of commit one can use tags). And because this is open source one does not need to login to jfrog.
If we indeed want to push this to jfrog (https://www.jfrog.com/confluence/display/JFROG/PyPI+Repositories) I believe I need to spend a few hours on this.

**Comment by shlomi-nx** [comment]
That is fine by me, but that would mean that tags needs to be created to correspond to the builds in JFrog, no?

**Comment by shlomi-nx** [comment]
We should put Python in JFrog, so that requirements.txt does not contain an opaque hash instead of a clear version string

**Comment by Emulebest** [comment]
Python SDK is already in JFrog, you can use the same versions as with Typescript SDK

**Comment by shlomi-nx** [comment]
oh! awesome, I will try that!

**Comment by shlomi-nx** [comment]
Perhaps we should add another line in the Readme table for python, just to be clear.

**Comment by Emulebest** [comment]
Closed via #63166a444c9e1a9904a82e5c4bad3c764027e3ac
