### ISSUE TITLE
PATCH update_status doesn't work well with arrays

### ISSUE THREAD

**Issue by Emulebest** [nutanix/papiea#415]

**Comment by shlomi-nx** [comment]
Lets continue the discussion we had https://github.com/nutanix/papiea/issues/411#issuecomment-642391344 here.

Looking into it deeper, it seems that mongo only uses dot.notation for top level elements. This means that the library we are using has a bug (https://github.com/aggregion/mongo-dot-notation-tool/issues/2). However, since this library is a single 166 LOC file, we could potentially just embed that in and modify as needed - or right from scratch. 

What we need, in order to trivially achieve the `update_status has replace semantics for vectors` is to only collapse to dot.notation until we reach a terminal or a vector. That should be the simplest and most straight forward solution to this.

We could later add some more elaborate interface for vector management on status updates, but I do believe that just replacing the full vector will be better and easier.

In terms of race-conditions. The providers should be able to recover from bad `status` by either discovering the real state on the resource, or by rerunning the operation which gets it to the right `status` value. Given that operations should anyway be idempotent these two things could collapse into one.

For status fields that are used more as a "scratch-pad" than a reflection of an observable state - those would need a separate discussion. It may be worthwhile to have some specific notion of a scratch-pad which may be guarded by some form of `scratch-version`.

**Comment by shlomi-nx** [comment]
I made the required changes. Perhaps some testing could be added, but it should generally work now. Please see #420. 

The semantics for `update_status` is - it will only update the fields defined in it. Everything inside a vector will be replaced and not merged.
