### ISSUE TITLE
Rename `IntentfulTask` to `IntentWatcher` - the name task is misleading

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea#422]
@joshua-berry-ntnx, @Ntnx-Igor-Korotach if you think of a better name please post here

**Comment by joshua-berry-ntnx** [comment]
Brainstorming a few more ideas, thinking along the lines of "unresolved"/"pending"/"incomplete", "intent"/"spec", "change"/"update"/"diff", probably there are more synonyms...:

- UnresolvedIntent
- IntentChange
- PendingSpecChange
- UnresolvedDiff (I don't really like "diff" because the "diff" is distinct from the actions we are taking to resolve it)
- PendingDiff

**Comment by shlomi-nx** [comment]
I always thought of this more as a "watcher" of an intent spec. I don't like `pending`, since its brings the connotation of a task, maybe `unresolved`..

**Comment by Emulebest** [comment]
> I always thought of this more as a "watcher" of an intent spec. I don't like `pending`, since its brings the connotation of a task, maybe `unresolved`..

I sort of agree with the idea, but... I feel like the general purpose of this thing even having a name like `IntentStatusAndInfoTracker (really bad but precise name)` is not going to be evident from the first glance by a papiea newcomer. Thus we'll still have some explaining to do in the docs. We are already centered around intent and the ecosystem of it, so maybe we could consider giving people something that sticks to them to understand and remember better?

The variants are:
custodian, warden, watchman
