### ISSUE TITLE
GET on an entity should also return an IntentWatcher if the entity has one

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea#423]
This way the caller will get all available info on an entity. 

(`IntentWatcher` - nutanix/papiea#422)

duplicate of #562

**Comment by shlomi-nx** [comment]
There may be more than a single `IntentWatcher` on an entity, but only a single one which is `Active`. 

The thing here is that it may not be straight-forward for users to tell which change they should get out of the response. E.g:

1. User A made an intent, `spec_version 1`
2. User B made a conflicting intent, `spec_version 2`
3. `IntentWatcher` for `spec_version 1` is now outdated
4. User A `GET` the entity, what should he see? How could he easily (aka programmatically) see that his intent got outdated?
    - If he sees all intents, he needs to search - he might as well just `GET` the `IntentWatcher`
    - If he sees only to `Active` one, he needs to find out its not his and the do `GET` on his, to see if it got outdated or not..

Having seconds thoughts on this.. What do you think?

@joshua-berry-ntnx , @Ntnx-Igor-Korotach

**Comment by joshua-berry-ntnx** [comment]
Here is a basic question: What is the IntentWatcher (or whatever we decide to call it per #422) for?

Let's say a client wants to track its outstanding/unresolved intent. There are actually three levels of this:

1. Just don't. The client may not care at all—for example, BMaaS provisioning API sets an intent and then returns the machine, expecting the caller to poll to determine when the machine is ready (or failed).
2. Coarse-grained — the client cares about ANY/EVERY subsequent intent change.
3. Fine-grained — the client only cares about "conflicting" intent changes (e.g. to the same properties that were changed by the client).

Level 1 is easy.  For level 2, IMO the easiest way for a client to see that his intent was superseded is actually just to look at `metadata.spec_version` and not bother with IntentWatchers at all. The client already knows what `spec_version` it set when declaring its intent, and can simply check if it's changed.

Level 3 is (only) a little harder. For those clients that DO want some more fine-grained method of determining whether their intent was superseded or not, I _still_ think it's easiest to remember and compare `spec_version` and the specific fields/parameters the client cares about. In fact, I think this is probably more correct, because the client is then forced to deal directly in terms of the intent that was set and the conflicting intent (expressed as spec properties).

I worry about exposing too much detail through the IntentWatcher, because it affords clients opportunities to ignore conflicts they might care about—client programmers might look at an IntentWatcher, see it's been resolved, and assume what they asked for is "done" when that might not be true (and is a very procedural way of thinking anyway—intents are never "done").

So I instead see an IntentWatcher as more of a diagnostic mechanism—clients might legitimately be interested in knowing WHY their intent hasn't (yet?) been resolved, and I think we can present information here (perhaps indexed by `spec_version`) on the _mechanics_ of resolving an intent (errors, maybe even some status/progress information, etc.) without needing to expose what the intent actually _is_ (which should always only be captured in `spec`).

This is admittedly a perhaps-radical change in how IntentWatchers are intended (ha) to be used, but I think it's a good one. So what would that look like?

First, I think it's OK to expose unresolved/active IntentWatchers through the entity GET API—I doubt there will ever be so many that this list becomes unwieldy/difficult to search. (I would not expose _superseded_ or completed IntentWatchers though.) This could be done through another top-level property on the entity (alongside `spec`, `status` and `metadata`).

Second, I think it should only expose `spec_version` (for client correlation) and error information, and I could maybe be convinced to include progress/status as well; something like:

```js
spec: {...},
status: {...},
intents: [
    {
        spec_version: 4,
        status: 'active',
        progress: { /* idk something provider-defined */ },
        errors: [...] // if any
    },
    {
        spec_version: 5,
        status: 'pending'
    },
]
```

Again, I'm not necessarily recommending we include `status` and `progress`, but we could if we want. `progress` in particular I worry about exposing too many procedural details, and we already have `<entity>.status` after all. We could also expose the diff if we really want, although that runs a similar risk of becoming too procedural. It's really about `errors` (and maybe `status` if we want some way to report that we just haven't tried to resolve something yet).

Ultimately, though, I think we can probably drop the notion of an IntentWatcher UUID (at least, as visible to clients) and the separate watcher/"task" API entirely (unless we find in practice that the list of intents gets too large).

What are your thoughts? Is there some use case I've missed?

**Comment by Emulebest** [comment]
> Here is a basic question: What is the IntentWatcher (or whatever we decide to call it per #422) for?
> 
> Let's say a client wants to track its outstanding/unresolved intent. There are actually three levels of this:
> 
> 1. Just don't. The client may not care at all—for example, BMaaS provisioning API sets an intent and then returns the machine, expecting the caller to poll to determine when the machine is ready (or failed).
> 2. Coarse-grained — the client cares about ANY/EVERY subsequent intent change.
> 3. Fine-grained — the client only cares about "conflicting" intent changes (e.g. to the same properties that were changed by the client).
> 
> Level 1 is easy. For level 2, IMO the easiest way for a client to see that his intent was superseded is actually just to look at `metadata.spec_version` and not bother with IntentWatchers at all. The client already knows what `spec_version` it set when declaring its intent, and can simply check if it's changed.
> 
> Level 3 is (only) a little harder. For those clients that DO want some more fine-grained method of determining whether their intent was superseded or not, I _still_ think it's easiest to remember and compare `spec_version` and the specific fields/parameters the client cares about. In fact, I think this is probably more correct, because the client is then forced to deal directly in terms of the intent that was set and the conflicting intent (expressed as spec properties).
> 
> I worry about exposing too much detail through the IntentWatcher, because it affords clients opportunities to ignore conflicts they might care about—client programmers might look at an IntentWatcher, see it's been resolved, and assume what they asked for is "done" when that might not be true (and is a very procedural way of thinking anyway—intents are never "done").
> 
> So I instead see an IntentWatcher as more of a diagnostic mechanism—clients might legitimately be interested in knowing WHY their intent hasn't (yet?) been resolved, and I think we can present information here (perhaps indexed by `spec_version`) on the _mechanics_ of resolving an intent (errors, maybe even some status/progress information, etc.) without needing to expose what the intent actually _is_ (which should always only be captured in `spec`).
> 
> This is admittedly a perhaps-radical change in how IntentWatchers are intended (ha) to be used, but I think it's a good one. So what would that look like?
> 
> First, I think it's OK to expose unresolved/active IntentWatchers through the entity GET API—I doubt there will ever be so many that this list becomes unwieldy/difficult to search. (I would not expose _superseded_ or completed IntentWatchers though.) This could be done through another top-level property on the entity (alongside `spec`, `status` and `metadata`).
> 
> Second, I think it should only expose `spec_version` (for client correlation) and error information, and I could maybe be convinced to include progress/status as well; something like:
> 
> ```js
> spec: {...},
> status: {...},
> intents: [ // <- needs a better name
>     {
>         spec_version: 4,
>         status: 'active',
>         progress: { /* idk something provider-defined */ },
>         errors: [...] // if any
>     },
>     {
>         spec_version: 5,
>         status: 'pending'
>     },
> ]
> ```
> 
> Again, I'm not necessarily recommending we include `status` and `progress`, but we could if we want. `progress` in particular I worry about exposing too many procedural details, and we already have `<entity>.status` after all. We could also expose the diff if we really want, although that runs a similar risk of becoming too procedural. It's really about `errors` (and maybe `status` if we want some way to report that we just haven't tried to resolve something yet).
> 
> Ultimately, though, I think we can probably drop the notion of an IntentWatcher UUID (at least, as visible to clients) and the separate watcher/"task" API entirely (unless we find in practice that the list of intents gets too large).
> 
> What are your thoughts? Is there some use case I've missed?

I am not too much into the idea of not showing the original intent's aim (a.k.a spec change). I like the idea of it being simple/simpler than what we already have though. Maybe we could add querying by spec versions to make all the spec changes into history so that combined with intents + spec versions they could represent the whole picture. I also upvote the idea of giving a sorted list of intents, it shouldn't be too big anyways

**Comment by joshua-berry-ntnx** [comment]
Perhaps we could show only the diff for each spec change? Or maybe just remaining/active diffs that haven't been superseded for a particular spec change.

The question for me is: how might clients be expected to use that information?

**Comment by shlomi-nx** [comment]
I am still not quite convinced. In this proposal, how would a client find which of the returned watchers is his? doe he now need to loop over an array and check spec-version? Do we make it an ordered map so he can easily find out? How many do we keep? For how long?

I am starting to think that what we already have is sufficiently good..

**Comment by shlomi-nx** [comment]
> IntentWatcher as more of a diagnostic mechanism—clients might legitimately be interested in knowing WHY their intent hasn't (yet?) been resolved

The concept of the watcher is not to diagnose problems. It is to be able to "block" on an intent and get notification when it is done and the client can move to its next step. 

> Ultimately, though, I think we can probably drop the notion of an IntentWatcher UUID (at least, as visible to clients) and the separate watcher/"task" API entirely (unless we find in practice that the list of intents gets too large).

We cannot drop this, as this is the first thing any client would ask you: `How do I know my intent has completed`. Asking them to manually get and diff spec/status is an unacceptable answer.

Clients will need a way to track resolution of their intent. This "resolution" is defined by the semantics we introduced by the watcher, where success means **there was a point in time when it was completed**. Diagnosing problems is an addition on top of that. Kinda like exceptions - they are used to establish flow-control, not diagnostics. Diagnosing problems with them is a side effect, even though a very useful one.

**Comment by joshua-berry-ntnx** [comment]
Had an offline discussion with Shlomi on this and I think we basically agree—the major value of an intent watcher is to get info on whether your intent has been resolved yet and if there are any problems preventing it from being resolved. The key distinction is whether the intent is resolved or unresolved.

Knowing whether an intent was superseded or actually completed isn't helpful to clients who need to make a decision about what to do next, because the entity spec/status are subject to change at any time without the client's knowledge. But it does provide a stepping-stone for folks used to the procedural world to start thinking about how to program in an intentful way, because it frames the notion of "resolving an intent" in a way that's more easily understandable.

Coming back to the API discussion, I still think it's convenient to present unresolved intents alongside entity spec/status as part of a normal GET; this way clients can fetch all relevant info about a particular entity in one call (absent pathological cases like too many unresolved intents). But this is a convenience; it's not strictly necessary, as I don't think Papiea itself would be able to provide any consistency guarantees anyway when fetching spec+status/intents in one GET vs. two.

**Comment by shlomi-nx** [comment]
I am putting this one on hold for now. Lets revisit this.
