### ISSUE TITLE
Makefile has bad dependencies

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea#448]
Please see the comment and current workaround in https://github.com/nutanix/papiea/pull/446/commits/2c570fcc1e845e02d7374244b22138405d5ad14e

Copied here for easy access:
```
Makefile hacks to fix dependencies

The dependencies throughout the Makefile were improperly specified, so
nothing was ever getting rebuilt if it already existed.  For now, I have
made everything `.PHONY` to work around this, but we need to specify
proper dependencies on the non-PHONY targets.

Also, I have changed the `default` target to actually build the project,
rather than simply building the benchmarks.  This was rather surprising
(to say the least).

Also also, I broke up the giant `.PHONY` target into tagging individual
targets.  Having one large `.PHONY` is not best practice because it's
very hard to see whether an individual target has been tagged `.PHONY`
or not.
```

Please fix this properly.

**Comment by Emulebest** [comment]
`The dependencies throughout the Makefile were improperly specified, so
nothing was ever getting rebuilt if it already existed.`
This was intentional, wasn't it? To do a full rebuild you'd need `make clean-all && make` didn't that work?

**Comment by joshua-berry-ntnx** [comment]
Incremental builds did not work at all. If you had built Papiea once, you could never rebuild it without doing `make clean` first.

**Comment by joshua-berry-ntnx** [comment]
I should note the hack I put isn't entirely correct, either, but it's incorrect in the other direction—it was the most expedient thing to get Papiea to rebuild. I think the next step is to look at some of those `.PHONY` targets, see which ones really are `.PHONY` and which aren't, and put proper dependencies so the non-PHONY targets are rebuilt appropriately.

**Comment by Emulebest** [comment]
> Incremental builds did not work at all. If you had built Papiea once, you could never rebuild it without doing `make clean` first.

To be honest, we never had proper incremental builds in Papiea, if you had modified `papiea-sdk` for example, then you'd need to manually rebuild it. With yarn this is even more problematic since it needs to do `yarn install` then `yarn run build` and then copy /build folders to all the node_modules of dependants.

I propose to fix the `.PHONY` hack here but introduce the automatic incremental builds as other less critical issue because `make clean-all && make` is quite fast ATM

**Comment by joshua-berry-ntnx** [comment]
Ahhh I see. So a lot of things will end up being PHONY anyway because (for example) the node_modules of -sdk will depend on the build of -core, and so on.

If incremental builds truly are not possible, then I would prefer to keep the hack I put in before. Requiring `make clean-all` before `make` is not a good developer experience—`make` with no arguments is the common thing most projects support, and causing `make` to silently fail to rebuild stuff will end up wasting people's time on debugging a basic issue the makefile should already be taking care of.

**Comment by joshua-berry-ntnx** [comment]
IMO the basic requirement is: `make` with no arguments, by itself, must produce working, up-to-date build artifacts for every important/major user-facing thing in the repo. If something is out-of-date, it must be rebuilt (even if that means we are effectively doing a `make clean-all` or whatever internally).

**Comment by Emulebest** [comment]
> IMO the basic requirement is: `make` with no arguments, by itself, must produce working, up-to-date build artifacts for every important/major user-facing thing in the repo. If something is out-of-date, it must be rebuilt (even if that means we are effectively doing a `make clean-all` or whatever internally).

I got the idea. I am not saying they are not possible, rather we haven't had them set up at any point in time. I will investigate the possibility in another issue

**Comment by Emulebest** [comment]
related to #453

**Comment by Emulebest** [comment]
Closing due to above being open. Hacked in #446
