### ISSUE TITLE
Provide E2E testing for all SDKs

### ISSUE THREAD

**Issue by Emulebest** [nutanix/papiea#486]
As noted in
Build a sample/reference provider for each SDK which is identical/has consistent behavior across all SDKs, and shows all the major SDK features (each type of procedure, different entity kinds, different kinds of SFSes)

Write system-level tests which call papiea-client in each language "as if" the test were a user, which use the aforementioned reference provider(s), to make sure the behavior of engine and SDK is correct/consistent across languages

**Comment by shlomi-nx** [comment]
# Idea for a test provider
A simple provider could be a "file store"

# Kinds
## Directory
### Spec fields
1. Path
2. List of sub-paths references
3. List of file references

### Procedures
1. Entity level: Size of path (recursive/none-recursive)
2. Provider level: format - delete everything and add a new root `/` path

## File
### Spec fields
1. File name
2. Path reference
3. File content

Add intentful handlers for each of these

### Status only fields
1. Last modified
2. Size

These values should be computed

### Procedures
#### Entity level
1. Count lines - assuming file is ASCII, count the newlines in the file
2. Move file - moves to file to a new directory, given as `/dir/name`. If directory does not exist create it.

#### Kind level
1. batch-rename - rename all files matching some glob: `rename('*.txt', '*.txt.old')` in any directory

**Comment by joshua-berry-ntnx** [comment]
Spoke with Nitesh and Igor about this further and I think we need to revise/simplify this somewhat so it's a little clearer. The main change is we want to get rid of any recursion, because that will end up introducing a lot of unnecessary complexity to what should be a relatively simple example. So instead we are going to aim for a fairly simple object store. We can always expand on this later if needed for additional testing.

The main features/functionality are as follows:
* Each bucket has a name.
* Buckets may contain/reference objects, but cannot contain/reference other buckets.
* Each bucket maintains a list of name/object pairs.
* An object may be contained by multiple buckets, and/or may have multiple names within the same bucket.
* The object itself knows all the paths (bucket name + object name) where it can be found.

## Bucket
### Fields
1. `name`: string
2. `objects`: {`name`: string, `reference`: {`kind`: 'object', `uuid`: string}}

### Kind Procedures
1. `ensure_exists` - Create a new bucket with the specified name or return a reference to a bucket with that name if one already exists

### Entity Procedures
1. `create` - Creates a new object in the bucket with the specified name and returns a reference to it. Fails if the name is already in use by another object.
2. `link` - Adds an existing object in the bucket with the specified name. Fails if the name is already in use by another object.
3. `unlink` - Removes an existing object from the bucket with the specified name, but leaves the object intact.

NOTE: These procedures should largely just update spec and let the intent handlers work out how to resolve the difference. As much as possible should be pushed into the intent handlers.

### Intent Changes
1. Updating `name` must change all the references in each object so the new bucket_name is used.
2. Updating `objects` must add/delete/update references as appropriate in the referred-to objects

## Object

### Fields
1. `content`: string

### Status-Only Fields
1. `references`: {`bucket_name`: string, `object_name`: string, `bucket_ref`: {`uuid`: string, `kind`: 'bucket'}[] — Array of buckets which refer to this object
2. `modification_time`: number

### Intent Changes
1. Updating `content` should set the `modification_time` to now

**Comment by joshua-berry-ntnx** [comment]
This is a good list. But in general, I think we should try to organize it in terms of the things we want to test in Papiea, not the provider itself (which is just an example to enable Papiea testing). For example, the create test cases should probably be written like:
* Create entity with constructor (create a new unique bucket, should succeed)
* Create entity with failing constructor (create a duplicate bucket, should fail)
* Create entity with a kind procedure (call `ensure_exists` with duplicate bucket, should succeed)

These are the same test cases (although I added one for the kind procedure), but written in terms of Papiea, not the example provider.

Hope this makes sense—let me know if you want to get on a call to discuss further.

**Comment by nitesh-idnani1** [comment]
Based on the discussion, we need to mention the papiea features/procedures that are being tested by the tests above and keep the organisation same as described by me.
