### ISSUE TITLE
Custom entity constructors

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea#505]
Current `on-create` function is invoked on a newly-created entity by providing all spec fields. There are a number of reasons why this is not sufficient, among others we have the need to establish some constants which will be reflected as `status-only` fields, or the need to provide a higher level of abstraction than individual and exhaustive spec definition.

The idea is to leverage the existing procedures mechanism to establish a custom constructor.

# Definition

a custom constructor function is a function of type: `ConstructorCtx, Input->Entity`:
1. `ConstructorCtx` is a similar a procedure's context, with some additions, expanded below
2. `Input` is a custom schema defined in the same way as any procedure does
3. `Entity` is a 3-tuple consisting of the following:
  a. Partial `metadata` section - in the same way current entity creation POST accepts
  b. `spec` section - in the same way current entity create POST accepts
  c. `status` section - all the status fields to be set on this new entity

The custom constructor function will be invoked prior to the actual entity creation, and the returned `Entity` object will be created in Papiea.

`ConstructorCtx` will provide the ability to register a callback function that will execute after successful creation of the entity. 

# Flow
1. If the custom constructor function fail to return a valid `Entity` representation, no entity gets created and a proper error message and code is returned.
2. If the optional post-create function throws an error, the just created entity will get deleted and a proper error code will be returned. the failed post-create function should handle all cleanup as well
3. If both functions succeeds, the created `Entity` is returned to the user
4. Only after both functions succeeds, the entity is available for others to use (it is available for GET, PUT, DELETE)

# Example
```typescript

const the_kind = sdk.kind(...)

the_kind.on_create(InputSchema, (ctx: ConstructorCtx, input: Input):Entity => {
    // 1. Define the entity, run code etc
    let entity: Entity= {
        metadata: {uuid: "...", extension: {owner: "me"}},
        spec: {...},
        status: {...}
    }

    // 2. Register post creation closure, which wraps around the current variables
    ctx.post_create((created_entity: Entity):None->{
        // 4. Post create is a callback after creation:

        ctx.update_status(created_entity.metadata, {...})
    })

    // 3. Now create the entity
    return entity
}
```

# Exported swagger schema for the constructor
The default entity's create POST will be replaced by a the POST procedure registered using the `on-create` function. It's input will be that of the `Input` schema, and it's output will be a full `Entity`, the same as returned by `GET`.

No other `procedures` will be generated for the custom constructor, e.g. no `on-create` or `post-create` entries should be exposed via swagger spec.

If no custom constructor is defined, standard POST constructor will be created, as done today.

**Comment by abhi-nutanix** [comment]
Thanks @shlomi-nx for the proposal! 

I think it is confusing to call `the_kind.on_create` as constructor. We can stick with existing `kind.on_create()` which will be called when entity is created in Papiea.

We can provide another fn. `kind.constructor()` which acts like constructor to `create` the entity. When this returns the entity with success, the entity is created in papiea(equivalent to kind.create() that exists today).

The POST should be transparent. If kind.constructor() is registered, POST should accept the schema of the constructor and call the constructor else it behaves in the old way.

**Comment by joshua-berry-ntnx** [comment]
I have spent some time thinking about this as well, and had started my own proposal (which isn't finished yet). I am on board with everything you write above except `post_create`, and I think the issues with `post_create` might be fixable.

First, just for context, when I was thinking about how custom constructors might work, there are three problems I had in mind:

1. It is not possible to write a constructor which takes a simple set of parameters and then computes `spec` in an appropriate, implementation-defined way, because one cannot pass anything other than `spec` values themselves to the constructor.
   * For example, this makes it hard to write an entity which, as part of construction, allocates some resources from a pool of other entities according to some criteria (e.g. "I'm creating a *bar* and *bar* needs a *foo* which has some properties specified in the *bar* constructor").
2. It is not possible to define fields on an entity which are set only at construction time and then never changed (see also: #432). Ordinarily this could be done with `status-only` fields (and relying on the provider not to ever change them), but since it's not possible to pass anything other than `spec` fields to a constructor, it's not possible for clients to specify values for `status-only` fields at construction time. There are two ways around this, but both have problems:
   * Create a kind procedure to act as a factory function. This is problematic because the "real" constructor still needs to exist and is exposed to clients, creating ambiguity in the API spec about which one to use (constructor or factory).
   * Make these `status-only` fields be regular spec+status fields. This is problematic because clients could change the `spec` of these fields at any time, even though doing so is nonsense/not meaningful.
3. We might wish to make constructors truly idempotent in the strict sense—that is, if an object already exists, simply return it (rather than failing with an "already exists" error).  Or, we may want a constructor to be able to choose what to do based on implementation-specific criteria—return an existing entity, or create and return a new entity.
   * One hypothetical example of this might be a subnet—if a subnet with a particular CIDR is already defined, we may just want to return that subnet rather than creating a new one (e.g. because there is a requirement that subnet CIDRs must be unique within a network).

I think the proposal in the OP covers (1) and (2) but not (3). To cover (3), the constructor needs to be able to return an existing entity (not just a new one), and it's not clear to me how a post-create closure could work in that scenario. If you return an existing entity and register a `post_create`, does `post_create` still run? What happens if `post_create` fails in that situation?

Even if we forget about (3), it's not at all clear to me that deleting the entity on an unhandled exception in `post_create` is the right thing to do in every situation. I think the typical use case of `post_create` would be to arrange for some side-effects to happen—for example, setting up relationships between other existing entities and the new entity. Taking this example, if we fail part-way through setting up these relationships and Papiea deletes the entity, we may wind up with broken links to the new (now-deleted) entity. Worse, we may not be able to recover from this because deleting the partially-constructed entity caused us to lose information about that entity that might be needed to resolve the problem. I think in this situation, leaking the entity might be the better course of action.

### Even More Procedural Constructors

Again, I think all of the above is solvable and we could make `post_create` work. However, I think there's another approach that is both simpler to implement and use, and side-steps the above problems entirely. We can treat the constructor exactly like every other kind procedure (except with special syntax to `POST` to the kind itself), and expose a `create_entity` SDK API to the provider to make the actual database entry and pre-populate spec and status.

If a kind "opts in" by registering a constructor method, entity construction is entirely controlled by the provider, which must call `create_entity` at the appropriate point. Otherwise, entity construction works as it does today where Papiea provides a default constructor that is effectively just a `create_entity` that only pre-populates spec.

We can also optionally restrict constructors to returning only an entity of the appropriate kind, which I think achieves the (implied) goal of the OP to require constructors to all have similar semantics (by forcing Papiea itself to create the entity on behalf of the constructor, using the return value from the constructor procedure). However, this isn't necessary for correctness.

A complete example would look something like:

```ts
type SubnetEntity = {spec: {...}, status: {...}, metadata: {...}};
type Arguments = {network: ..., cidr: string};

subnet.on_post(
    {/* swagger */},
    async (ctx: Papiea.Context, args: Arguments): SubnetEntity => {
        const kind = ctx.kind('subnet');
        const matching = await kind.filter(
            {spec: {network: args.network, cidr: args.cidr}});

        // Is subnet already created? Just return it
        if (matching.entity_count >= 1) return matching.results[0];

        // Nope, let's create it
        const subnet = await ctx.create_entity('subnet', {
            spec: {used_ips: []},
            status: {network: args.network, cidr: args.cidr, ...},
        });

        // Register the subnet with its parent network (CAS loop for spec updates
        // omitted for brevity).
        try {
            const netkind = ctx.kind('network');
            let net = await netkind.get(args.network);
            net.spec.subnets.push({subnet: subnet.metadata});
            await netkind.update(net.metadata, net.spec);
        } catch (e) {
            // Let's assume there wasn't a conflict; CAS loop for spec updates
            // omitted for brevity.
            //
            // Delete is explicit so it's clear how errors are handled.
            await kind.delete(subnet);
            throw e;
        }

        return subnet;
    });
```

### Remove post_create itself

Another, more purist alternative might be to stick to the original proposal but remove `post_create` entirely. The argument here is that any of the side-effects, etc. that would be handled by `post_create` should instead be handled in an intentful way. This makes the constructor procedure itself be more pure, in the sense that such side-effects may only be done by returning an entity description with an appropriate `spec`. But I think this goes somewhat against Papiea's original philosophy of offering intentful features without forcing their use.

The other reason I don't like this is it requires more things to be placed in `spec` that only apply at construction time—continuing the above example, `network` would have to be in both spec and status, and an intent handler would need to be defined to ensure the subnet gets registered with its `network`. However, changing a subnet's network after it's already been created doesn't make any sense.

So I don't really like this last idea—would prefer to address the issues around `post_create` or go all-in on procedural construction. But I wanted to mention it here for completeness.

**Comment by joshua-berry-ntnx** [comment]
> We can provide another fn. `kind.constructor()` which acts like constructor to `create` the entity. When this returns the entity with success, the entity is created in papiea(equivalent to kind.create() that exists today). If `kind.on_create()` is registered, it will be called post entity creation(already existing behavior).

So @shlomi-nx and I discussed this early on (long before this proposal was written) and concluded it's not sufficient, because there is no way to pass information between pre- and post-constructor functions (where pre- in your case is `constructor` and post- is `on_create`), apart from putting it in the entity itself—which is not desirable because it may be private, irrelevant to the client, etc. That in turn led to @shlomi-nx's proposal you see above.

**Comment by shlomi-nx** [comment]
> We might wish to make constructors truly idempotent in the strict sense—that is, if an object already exists, simply return it (rather than failing with an "already exists" error). Or, we may want a constructor to be able to choose what to do based on implementation-specific criteria—return an existing entity, or create and return a new entity.
> * One hypothetical example of this might be a subnet—if a subnet with a particular CIDR is already defined, we may just want to return that subnet rather than creating a new one (e.g. because there is a requirement that subnet CIDRs must be unique within a network).

I disagree with this notion. A constructor is not an Idempotent by definition - it creates a new thing. If there is a problem creating, it should fail and user should consciously GET. We can later add an `upsert` procedure, but I wouldn't make it default by design as it may confuse clients. I see this as an inconsistent behavior.

**Comment by shlomi-nx** [comment]
> if we fail part-way through setting up these relationships and Papiea deletes the entity, we may wind up with broken links to the new (now-deleted) entity

This is why we have the post-create. You only make links after the entity is created. If you fail for some reason, you are in charge of the cleanup (this is written in the OP).

**Comment by shlomi-nx** [comment]
I left out an important detail, which I now edited in the original proposal. I paste it here to easily see the change:

> 4. Only after both functions succeeds, the entity is available for others to use (it is available for GET, PUT, DELETE)

**Comment by shlomi-nx** [comment]
@joshua-berry-ntnx I think you are reading too much into the `post_create`. This is just a mechanism for the separating the the logic between pre and post create. In other syntax I would do:

```typescript

kind.on_create(..., (ctx, input)=>{

// do stuff before creation

ctx.do_create(entity_with_status)

// do stuff after creation

})

```

@Ntnx-Igor-Korotach and I already discussed on this approach and it seems like getting this syntax to work was a tad more tedious. This is why I proposed the `post_create`, which is semantically equivalent.

The idea is that I do not want two seperate functions, `pre` and `post` - because this will encourage programmers to share state in an uncontrolled way. Enforcing this in a single function forces the shared state to be closed on rather than passed.

**Comment by shlomi-nx** [comment]
> I think it is confusing to call `the_kind.on_create` as constructor. We can stick with existing `kind.on_create()`

@abhi-nutanix , sorry, I don't see the difference. `the_kind.on_create` is the same as `kind.on_create` :| No one invokes `on_create` - clients simply do `POST http://.../entity {input: ...}` and Papiea calls it internally.

**Comment by abhi-nutanix** [comment]
@shlomi-nx Yes, my comment is based on the behavior that kind registers the `on_create` callback and papiea calls it. What I meant is what Josh summarized. Though, I am not convinced about the following (@joshua-berry-ntnx ):

> So @shlomi-nx and I discussed this early on (long before this proposal was written) and concluded it's not sufficient, because there is no way to pass information between pre- and post-constructor functions (where pre- in your case is `constructor` and post- is `on_create`), apart from putting it in the entity itself—which is not desirable because it may be private, irrelevant to the client, etc. That in turn led to @shlomi-nx's proposal you see above.

Constructor's job is to only crate the entity. on_create() should only act on the entity spec. There should be no information pass between the two by design. If any such use case is required, client can use custom procedures. We should overload or mix-up the pure constructor and on_create() semantics for very edge use cases.
