### ISSUE TITLE
Swagger spec incorrect for two different kinds with same procedure name

### ISSUE THREAD

**Issue by chauhan-nx** [nutanix/papiea#521]
Schema **expected** in swagger : [link redacted]
What it is : [link redacted]
[screenshot redacted]

**Comment by joshua-berry-ntnx** [comment]
@chauhan-nx Please keep in mind that Papiea is an open-source repo. I've removed your references to Nutanix internal components here. I've also updated the issue title accordingly.

Also, I think the Papiea developers will need some additional context (beyond links to the relevant source code) to be able to understand the issue. The issue here is that we have two different Papiea kinds, both of which have a procedure with the same name, and the Swagger spec for one procedure (perhaps the one that was registered last?) appears in both places.

**Comment by joshua-berry-ntnx** [comment]
BTW, I can confirm I'm seeing the same issue as @chauhan-nx—the schema for one `foo` kind procedure seems to be used for a `foo` kind procedure on a different kind.
