### ISSUE TITLE
Optional field can't be update again after set to null

### ISSUE THREAD

**Issue by NikitaChernenkoNutanix** [nutanix/papiea#528]
I have a field that is declared like this:

```
type: 'object',
     required: [ 'tenant_id'],
     properties: {
        tenant_id: {
            type: 'string',
            description:'id'
        }
     }
```

The following code firstly sets it to 'null' and after that tries to set a real value. 

```
const real_ref = {
    account_id: '74657374-696e-6700-0000-000000000000'
}
await update_status(metadata, {provider_ref: null})
await update_status(metadata, {provider_ref: real_ref})
```

I get:
```
 data: {
    error: {
        code: 500,
        errors: [
            {
                message: "Cannot create field 'account_id' in element {provider_ref: null}"
            }
        ],
        message: "Cannot create field 'account_id' in element {provider_ref: null}",
        type: 'server_error'
    }
}
```

When I try to set it to undefined instead, it says that I should use null.

The only workaround I use is to set some dummy value alongise with provider_ref: undefined. It works in such a case

**Comment by nitesh-idnani1** [comment]
@Ntnx-Igor-Korotach @NikitaChernenkoNutanix
As I understand there are two issues here, one is not being able to set null for the status field within the entity for which we can make change in the engine (the db part) to perform null value initialization.

Another issue I found out was that even if tenant_id field is set within the status, there is a requirement that it should be present every time we call update_status so we need to decide if we want to change that behavior or let it stay the same for validation reasons.

**Comment by nitesh-idnani1** [comment]
@Ntnx-Igor-Korotach  @NikitaChernenkoNutanix 
I've inspected the issue you're facing here and looks like it is coming from the swagger validate module, which does not allow for null values. A valid bypass would be to use an empty object `{}` instead, which is supported by the validator module if we change the set flags for the module.

**Comment by Emulebest** [comment]
@nitesh-idnani1 If the validator to be the problem, then we would get 400 error + a different error message so this shouldn't be it

**Comment by nitesh-idnani1** [comment]
Yes, the exception is coming from the mongo updateOne function, the reason for which is that the provider_ref is set to null first and then we update is using the dot notation in set field which uses the undefined nested fields and hence we get an error.
I'm thinking there are two ways to fix this, but both involve knowledge of the entity schema:

1. Inside the mongo update_status module instead of dot notation we can set values for the entire field i.e. instead of setting
`status.provider_ref.tenant_id: '1', status.provider_ref.account_id: '1'` we can use `status.provider_ref: {tenant_id: '1', account_id: '1'}`
which does not throw the error since we're setting the entire nested structure in the mongo db.

2. Another approach would be include a substitution logic in the papiea-engine (after the validator since validator does not allow empty object value) which basically checks if the field is a nested object and sets it to empty object instead of null which will avoid the mongo update error since the nested object is not set to null i.e. instead of passing
`{provider_ref: null}` we can substitute it with `{provider_ref: {}}`

**Comment by NikitaChernenkoNutanix** [comment]
@Emulebest , @nitesh-idnani1 
When I do `await update_status(metadata, {provider_ref: null})` now and retrieve the object again,
I get `entity.provider_ref === {}' instead of `entity.provider_ref === null || entity.provider_ref === undefined`

**Comment by Emulebest** [comment]
@NikitaChernenkoNutanix this is due to the implementation details. Long story short, we are changing every null to {}. Please consult with @shlomi-nx and @nitesh-idnani1 on this

**Comment by NikitaChernenkoNutanix** [comment]
@shlomi-nx, @nitesh-idnani1
Hi guys,
changing null to {} doesn't seems right.
First of all, when we don't have a value on an object field set initially we get 'null' for it. So now we have 2 'blank' states 'null' and '{}'.
Secondly, if we have an object with only optional fields, '{}' is a valid value for it and it doesn't mean that the object value is absent. It's present but with all optional fields omitted. So we can't treat each '{}' as 'null'

**Comment by shlomi-nx** [comment]
@NikitaChernenkoNutanix thanks for you insightful comment.

@Emulebest, @nitesh-idnani1 Should we investigate the other approach suggested here:

> 1. Inside the mongo update_status module instead of dot notation we can set values for the entire field i.e. instead of setting
>    `status.provider_ref.tenant_id: '1', status.provider_ref.account_id: '1'` we can use `status.provider_ref: {tenant_id: '1', account_id: '1'}`
>    which does not throw the error since we're setting the entire nested structure in the mongo db.

One caveat in this approach is that it may need to do that recursive. Perhaps a solution could be the something like the following:
1. try dot notation
2. if fails, look at the related schema, find next object
3. if no next object, return error
3. construct partial dot notation with explicit object try again, goto 2

**Comment by shlomi-nx** [comment]
After some discussion we came to another proposal. Trying to think deeper at the problem, we realized that meaningful semantics for Papiea's `update_status` API could be `null fields are not allowed`. This effectively means that fields which are set to `null` value are effectively removed from the database. 

This solves the problem in the following way:
1. Instead of not being able to differentiate between an empty object and a null value (as the current solution does), we decide to not be able to differentiate between a null value and a missing (undefined) field. This seems like a better, more coherent approach
1. mongo's dot-notation works fine if the field does not exists, but fails if the field equals to null. This solves the original problem. 

Lets see an example:

1. Create a new entity
    ```
     > db.entity.insert({shlomi:4})
     WriteResult({ "nInserted" : 1 })
     ```
1. Update with dot-notation an inner field
    ```
    > db.entity.update({shlomi:4},{$set:{"a.b":5}})
    WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
    ```

2. Check it
    ```
    > db.entity.find({shlomi:4})
    { "_id" : ObjectId("5fc6a63f6f767737587bd631"), "shlomi" : 4, "a" : { "b" : 5 } }
    ```

1.  **Original problem we faced**
1.  Set field a to null instead of removing it completly:
    ```
    > db.entity.update({shlomi:4},{$set:{"a":null}})
    WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
    ```

1. look at it
    ```
    > db.entity.find({shlomi:4})
    { "_id" : ObjectId("5fc6a63f6f767737587bd631"), "shlomi" : 4, "a" : null }
    ````
1.  Now update again using dot-notation on an inner field, which fails as this issue describes
    ````
    > db.entity.update({shlomi:4},{$set:{"a.b":5}})
    WriteResult({
            "nMatched" : 0,
            "nUpserted" : 0,
            "nModified" : 0,
            "writeError" : {
                    "code" : 28,
                    "errmsg" : "Cannot create field 'b' in element {a: null}"
            }
    })
    ````
1. **The proposed solution**
1. Clean up
    ```
    > db.entity.deleteOne({shlomi:4})
    { "acknowledged" : true, "deletedCount" : 1 }
    ```
1. Create the entity again
    ```
    > db.entity.insert({shlomi:4})
    WriteResult({ "nInserted" : 1 })
    ```

1. Dot-notation update on none-existent inner field
    ```
    > db.entity.update({shlomi:4},{$set:{"a.b":5}})
    WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
    ```
1. This time, instead of setting to null, we are removing the field completely
    ```
    > db.entity.update({shlomi:4},{$unset:{"a":null}})
    WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
    ```
1. Which brings us to the original state right after insert, so that setting the nonexistent inner field succeeds
    ```
    > db.entity.update({shlomi:4},{$set:{"a.b":5}})
    WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
    ```

1. Check it:
    ```
    > db.entity.find({shlomi:4})
    { "_id" : ObjectId("5fc6a6806f767737587bd632"), "shlomi" : 4, "a" : { "b" : 5 } }
    ```

**Comment by shlomi-nx** [comment]
@joshua-berry-ntnx to test this fix with current bmaas
