### ISSUE TITLE
The error message with error code 500 is not push back to client. 

### ISSUE THREAD

**Issue by yitingwnutanix** [nutanix/papiea#538]
### System Details

- **Papiea Engine version**: nutanix-docker.jfrog.io/papiea:0.7.20_1657
- **Papiea SDK version:** 0.7.20+1657
- **Papiea Client version:** 0.7.20+1657

### Describe the Bug

The error message with error code 500 is not sent back to client, which makes it hard to debug the error on client side. 
I only have the following messages:
```
Request failed with status code 500
at createError (node_modules/axios/lib/core/createError.js:16:15)
at settle (node_modules/axios/lib/core/settle.js:18:12)
at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:202:11)
```

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by joshua-berry-ntnx** [comment]
Context here is that papiea-client was receiving a 500 thrown from the engine, because of a procedure which failed in a provider.

Rather than sending a generic 500 "Procedure invocation failed" message, I think it would be useful if, in debug mode only, we could send details of the procedure failure that happened in the provider (exception, stack trace, etc.) from the sdk, through the engine, all the way back to the caller (client). This would make it easier to debug while writing providers (rather than having to correlate two different logs to see what was going on).
