### ISSUE TITLE
Make sure nullable fields are handled properly or excluded

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#611]
As part of #596, I realized there may be a conflict in how Papiea is handling schemata vs. its `update_status` behavior. Specifically, if a field is `nullable` per [the Swagger spec](https://swagger.io/specification/#schema-nullable), but not `required`, it is possible the field could be absent entirely, have an explicit value of `null`, or have an actual value.

There is no way to correctly set such a field to `null` with `update_status()` right now, because `update_status()` assumes that explicitly setting a field to `null` should remove it entirely.

We should either figure out a way to differentiate field removal vs. explicitly assigning `null` in the `update_status()` API, or we should disallow `nullable` fields entirely.

**Comment by Emulebest** [comment]
@shlomi-nx @joshua-berry-ntnx Thinking about this more I have a few opinions on that. Firstly, I am against removing/disallowing Swagger standardized keywords (in our case `nullable`). Why so?
People are already used to having nullable alternatives, all the popular static languages have this form of semantics (either built-in like C# or opt-in like Java). Moreover, this is a staple of Swagger itself. Without this providers are inclined to go into the contest of designing null alternatives ("", "null", 0, etc.) and I don't think this is good for portability and interoperability of different provider written resources.
 
Secondly, If we have decided for papiea to be based on Swagger, limiting Swagger's possibilities to suit very narrow situation seems... unreasonable to me. We can expand on it, like `x-papiea-field`, but not limit the framework/contract.

Finally, We already have a lot of different not so strict cases, most notably:
1) Update Status with arrays (we disallow this)
2) Custom constructor input validation (has 3 different usage patterns)
and a bunch of smaller ones that IMO makes papiea harder to document and understand for newcomers and even seasoned devs (just look at Nikita Chernenko's issue).

Coming back to the topic of nullable. One approach is to deduce your intent (nothing to do with intentful) while updating status, examples:

State:
```
[
  {
    "key": 1,
    "a": {
        "b": 1
    }
  }
]
```
Update in a form of:
```
  {
    "key": 1,
    "a": null
  }
```
Result:
```
  {
    "key": 1,
    "a": null
  }
```

State:
```
[
  {
    "key": 1,
    "a": null
  }
]
```

Update in a form of:
```
  {
    "key": 1,
    "a": {
        "b": 1
    }
  }
```
Result (notice we didn't use dot-notation sematics):
```
  {
    "key": 1,
    "a": {
        "b": 1
    }
  }
```
Thus, try to use replace status semantics if there is no field or it is null in the current schema, otherwise you update status semantics (dot-notation transform). Also nullifying with replace status endpoint, while updating with update status endpoint is still an option.


The second approach we might want to explore is introducing CAS (optimistic locking) for status as well and do the updates in the same way we do spec updates. I see this as a more preferable way because it reduces user's complexity by sticking to something familiar, if there are no cases where this limits papiea's general abilities (haven't found a single case yet myself).

**Comment by Emulebest** [comment]
@shlomi-nx Took some more time to think on the topic. I believe the notion of `want to have nullable field - just don't make it required` is fine with me as long as we provide a good warning/error message on using the `nullable` property

**Comment by Emulebest** [comment]
@shlomi-nx @joshua-berry-ntnx @nitesh-idnani1 Were there any agreements reached in regards to this issue?

**Comment by joshua-berry-ntnx** [comment]
IIRC we had agreed that we don't need to support `nullable`, and we should reject schemas with `nullable`. We can simply tell people to make the field not-`required` if need be.

If someone comes back later with a compelling use case, we can always revisit this. Adding support for something is always easier than removing support. ;)
