### ISSUE TITLE
Propagate errors with complete information

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#633]
### System Details

- **Papiea version**: 0.9.27 [all components]

### Describe the Bug

There are a few situations where relevant error information is swallowed because exceptions are being re-thrown or are not being translated correctly across API boundaries. Please take a systematic look at all the places where we are re-wrapping exceptions and either stop doing this entirely or wrap them with the full context/info from the original error.

### Bug information
There are a couple places where we need to take special care:

**Custom Constructors:** Errors are swallowed/wrapped with some error that looks like "On Create couldn't be called; ..." and the original error details (except for the message) are lost. This "On Create couldn't be called" message is redundant; presumably the caller knows they are calling a constructor.

**Procedure Invocations:** Here again we have some wrapping which adds a redundant "Procedure invocation failed" message and again details are lost in the exception that's being thrown.

There is also some "Papiea encountered unexpected error" wrapping which shows up in the log; I'm not sure where this is coming from (or whether it's relevant yet).

This gets worse when crossing API boundaries—I don't understand how/why this is happening yet, but I have seen one case in which a procedure was calling a custom constructor, which threw an exception, and somehow by the time the error made it back to the client (who called the procedure), the error had been lost entirely and was simply being reported as `Procedure invocation failed.` with a sub-error `Error while making request` and no further details.

### Expected/Actual Behavior

I expect the exception raised in the custom constructor to be propagated back through the procedure (as an API-client exception, which then bubbles up to the SDK/context) and to the caller without information being lost.

### Steps to Reproduce
The specific steps are highly provider-dependent; I can share logs offline which show the entire path of the exception in question.

### Impact
Wasted time digging through logs to find more complete error information. This gets especially bad if the people doing the testing don't have complete access to dig around in the internal logs for Papiea/the provider themselves (and need to involve someone from another team to get a complete picture of what happened).

### Additional Details

I think this will require some design/design thinking to understand and clearly define how errors flow through the system, especially when multiple providers and/or nested calls through Papiea are involved. Especially because we need to be careful, once we start using Papiea in production, about what error information we return to the caller.

But, even without a complete design, if we can take some immediate steps to avoid re-wrapping exceptions and make sure they are propagated with complete information, that would be really helpful.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by joshua-berry-ntnx** [comment]
To add more thoughts: I'm honestly not sure how much of this should be handled by Papiea vs. the providers, but that's where I think some design is warranted. If some help is needed to propagate errors correctly to/through a provider, it would be great to have a clear contract defined for this.

What should a provider throw? What form should it take to be recognized and propagated correctly? etc.

**Comment by nitesh-idnani1** [comment]
Yes, we were missing the on create error handling in the papiea response logic. I've added that as part of the improve logging PR.
Reference:
https://github.com/nutanix/papiea/blob/dfb71930b9192723b7a1d4ddc01e6199cd23924b/papiea-engine/src/errors/papiea_error_impl.ts#L107

I would suggest to use the latest papiea version and try the tests. After that, it would be easy to define what the issue is and also what the requirements for the contract should be.

**Comment by Emulebest** [comment]
@joshua-berry-ntnx This has another pitfall of showing provider error details to the client invoking a handler, so the detail swallowing was done on purpose that time. Maybe we should log errors to papiea but not send any error details back to client?

**Comment by nitesh-idnani1** [comment]
Also, things like "Procedure invocation failed" / "Validation failed" / "Permission denied" is the summary for the error thrown by papiea. For debugging purposes and understanding the actual errors it's better to look into the "errors" field returned in the papiea response rather than the "message" field.

I can probably rename the message field to something like summary or error type, so that the user knows what values to expect for it.

**Comment by nitesh-idnani1** [comment]
@joshua-berry-ntnx @shlomi-nx @Emulebest 
So far, I'm thinking of the following structure for the base error class and one of the extended classes (BadRequestError):

Base error class (extends JS Error which includes the name and stack fields):
```
class PapieaException extends Error {
    cause: string;
    solution?: string;
    entity_info?: PapieaExceptionContext;
    sub_errors?: PapieaErrorDetails[];
}
```

BadRequest error class (extends base error):
```
export class BadRequestError extends PapieaException {

    constructor(error: PapieaErrorDetails) {
        super(error);
        this.name = PapieaError.BadRequest
        Object.setPrototypeOf(this, BadRequestError.prototype);
    }
}
```

Error Details interface to store the error related fields easily
```
export interface PapieaErrorDetails {
    cause: string;
    solution?: string;
    entity_info?: PapieaExceptionContext;
    sub_errors?: PapieaErrorDetails[];
}
```

Example for throwing error:
```
throw new BadRequestError({
    cause: 'Received wrong field',
    solution: 'Correct fields is x',
    entity_info: { provider_prefix: prefix, provider_version: version, kind_name: kind_name },
    sub_errors: [
        ...
    ]
})
```

Let me know if you'd like to change anything in the above scheme.

**Comment by shlomi-nx** [comment]
In our discussion, the `cause` was actually a reference to a previous exception, not a string. 
That is how I see the base class: 

```typescript
class PapieaException extends Error {
    cause: Error,
    message: string; // Should contain detailed error message and possible resolution
    entity_info?: PapieaExceptionContext;

    constructor(message, entity_info?, cause?)

    getDetailedStackTrace(): String[] {
       if (cause == null) return []
       return getDetailedStackTrace(cause).append(this.stacktrace()) // order TBD
    }

    getDetailedMessage(): String[] {
        if (cause == null) return []
        return getDetailedMessage(cause).append(this.message) // order TBD
    }

    getDetails(): (String PapieaExceptionContext String)[] {
        const currentDetails = [(this.message, this.entity_info, this.stacktrace())]
        if (cause == null) return currentDetails
        return getDetails(cause).append(currentDetails)) // order TBD
    }
}
```

This way, the standard pattern of catch-and-rethrow would intuitively look like:

```typescript
try {
...
} catch (e) {
  throw new PapieaException("horrible things happened.", {horrible: "thing"}, e);
}
```

**Comment by nitesh-idnani1** [comment]
Thanks for the feedback, two points that I want to discuss:

- We need to set what information we need to include in the error message, since now we have three pieces in the message i.e. reason for the error + provider/kind related info (prefix/version/kind) + resolution for the error. I believe this will make up for a large error message, which can lead to some confusions for the end user.

- For the cause part, sorry I mismatched the fields. There's an exception for the field in the `Validation Error` class which wraps multiple (validation) errors within it. So, we have two options to deal with it:
1) Modify the type for cause to a list of errors to support all the extended error types, which will result in a redundant nesting for majority of the error types.
2) Modify the `Validation Error` class to take up one validation error at a time and throw it, which will make it difficult for the user in case of multiple validation issues, since now they'll have to make multiple calls and resolve the issue one at a time.

Let me know your thoughts on this and what would be a better approach for the problems discussed above.

**Comment by shlomi-nx** [comment]
In the general case, I am not sure that we need a list of causes instead of a single nested cause. The idea is that exceptions traverse the stack, so there really isn't a list of them.

In the specific case of Validation errors, @Ntnx-Igor-Korotach tried to follow [haskell Validation type](https://hackage.haskell.org/package/validation), which is an accumulative error type. The reason for this is to be able to show as many validation errors as possible in a single invocation, to reduce validation roundtrip. It's a very special case of error handling that differs than standard error propagation via exceptions (a.k.a the Either monad in haskell)

 Let's talk about this f2f, will be easier to nail this down.

**Comment by joshua-berry-ntnx** [comment]
First, one general suggestion: I know JavaScript treats errors like objects (in the OO sense), but I think we would be better-served thinking about them first as JSON/plain data structures and then translating that to JS (or Python) exceptions. How should detailed errors be exposed in the API?

So just starting with the API format and building a little bit on what's been proposed so far, I think something like this might work:

```ts
{
    "error": "ConstructorFailed",    // Machine-readable error type
    "message": "Failed to create 'bucket' entity",    // Human-readable message
    "papiea_context": {    // Provider/kind/entity/etc., maybe auth/role info?
        "provider": "test",
        "kind": "bucket"
    },
    "stack": "...",    // Stack trace
    "cause": {
        "error": "EntityNotFound",
        "message": "No such 'account' entity: <uuid>",
        "papiea_context": {
            "provider": "test",
            "kind": "account",
            "uuid": "<uuid>"
        },
        "stack": "..."

        // Additional error-specific and optional properties...
        "http_status": 404,
    }

    // Additional error-specific and optional properties...
}
```

Apart from the JSON format, the additional suggestions are:
* Have an `error` or similar property with a machine-readable error type, for easy testing/validation, log searching, checking for particular errors, etc. The `message` could be verbose, informative, change frequently etc., but the `error` should be a stable/constant, well-known string identifier.
* Rename `entity_info` to `papiea_context` (or similar). This makes it clear the info is added by Papiea itself, and leaves room in case there is additional info we want to put in here later like authentication info, etc. that's not directly related to provider/kind/entity.
* We could also have optional fields like `http_status` or similar to provide hints to the SDK/engine about how to package the error in HTTP, as well. (But we should probably default to 500 Internal Server Error if those aren't specified.)

In terms of expressing this in JS (and translating to JSON for an API response), I could see us having a base error type (perhaps with some nice accessors or derived properties like @shlomi-nx's suggestions), and perhaps pulling the `error` from the class name, or just as an additional constructor parameter. We do need to be able to wrap/standardize "foreign" exceptions which bubble up to the SDK, but this also seems manageable in a similar way.

The reverse translation (JSON to JS) is a little more challenging. Perhaps we could just throw an exception of the base error type, or maybe of some special remote error type, with the JSON contained inside. Callers would have to know to watch for this type specifically (rather than the original error type), but I don't think that's too much to ask.

**Comment by nitesh-idnani1** [comment]
Addressing @joshua-berry-ntnx comments,
I believe the structure will look similar to what you've mentioned above, except the stack trace will be hidden from the user but will be formatted and included in the papiea logs. The error response will also include certain standard fields like error code, error name, error message (generic) for all papiea exception types. For detailed message, we have the error_details field which will wrap the sub-error and so on.

For additional fields like status_code, etc. we'll have to modify the error types and add a new member since the Error class does not include code by default. However, as it currently works in Papiea, only the Procedure Invocation error type has a status code associated with itself, since it captures error coming from the procedure handlers registered by the user. I'm not sure, if we want to do this for the other error types, unless we're gaining something useful out of it. Anyways if the error needs more context, you can always specify those details in the papiea exception context structure.

Coming to processing error response as JSON, as I mentioned above we have certain standard fields which will give you a general overview of the error. Moreover, the error details field is set up to accept any error and process it as raw data, if it doesn't conform to the papiea error types.

I did not exactly understand the reverse translation part. Can you provide more clarification on that, thanks.

UPDATE: I've pushed the refined error design changes. Let's review this and then discuss what to add/change in the error handling design.
