### ISSUE TITLE
update_status() is a race condition waiting to happen

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea#665]
Many, probably even most of the races I have fixed in Customer-1 code involve update_status() in some form. Usually update_status() being done against some entity other than the one being operated on, based on information that may be out of date (e.g. a simple read/modify/write).

I know there's been a lot of resistance in the past to making update_status() atomic in some way, but we really need to find some way to make it harder to misuse, because otherwise people will continue to shoot themselves in the foot. Here are a couple quick ideas. I'm sure there's more we could do, let's discuss in the comments.

### Option 1: Make it Atomic

As I'd previously proposed informally/offline, have a `status_version` field which works like `spec_version` and require atomic updates of status fields. This makes status updates more heavyweight, but ensures developers must handle update conflicts if they want their code to work. (Or at least, it will be obvious when a race would have occurred, because things will randomly fail with update conflict errors.)

This is a "brute force" approach in the sense that it covers all the use cases, but does so in a way that pushes more complexity onto the application/developer. So while I'm not ready to discard this idea out of hand, I do understand the concerns with it.

### Option 2: Restrict it to Intent Handlers

Restrict the use of update_status() to only those situations where we can be sure it is synchronized with respect to other things going on with the entity. Right now, this means construction, destruction and intent handlers. So the ONLY allowable time/place to call update_status() would be from a destructor, or a running intent handler. This means it is no longer necessary to worry about atomicity at all, since there is already higher-level synchronization being done.

This raises an interesting challenge though—there are a few places where update_status() is used that are not covered by the above restriction:
1. A status change on one entity should be reflected (possibly in a different form) on another entity
2. An "out-of-band" status change must be triggered (e.g. thru a push notification/API call against the entity, background task, etc.)

I don't quite know what to do with these yet—such things should certainly be synchronized with intent handlers, but how? 

For (1), one thought I had was to turn any such "out-of-band" updates into a spec change which then triggers the status change. For example, such entities could have a "refresh_status" or similar spec/status field which outsiders could tweak to trigger a status update. Something like this could even be baked into the engine—define a special "refresh_status" procedure which is synchronized with intent handlers, gets called periodically by the engine, and could be called by outsiders, to re-compute any status fields.

However, (2) almost demands some type of generalized synchronization, since out-of-band updates can, by definition, happen at any time and while other things are going on.

One way to address both (1) and (2) might be to expose a generalized task-scheduling mechanism (which could also be used by intent handlers) to queue tasks to run against a particular entity. The task would have access to update_status() on that entity and be synchronized with all other tasks, intent handlers, creation/deletion, etc.

I haven't spent time to refine these ideas yet, but wanted to get them out of my head and at least start the discussion more formally. What do others think?

**Comment by nitesh-idnani1** [comment]
Adding discussion points based on the design meeting with @joshua-berry-ntnx @shlomi-nx. Feel free to add your comments/feedback to this @Emulebest.

### Problems with `update_status` (misuse):

1. **Race conditions in update_status**
In case of multiple processes/threads working on the same entity, we could run into a scenario where both the processes try to read and update the same entity status resulting in inconsistent behavior for that entity.

2. **Failure handling in case of multiple operations updates**
Consider a scenario wherein we update status for entity A from S1 -> S2, and for entity B from T1 -> T2. And in between the two update status calls, some other entity updates the status for entity A from S1 -> S3. Now, if the update status for entity B (T1 -> T2) fails, we have no consistent way to rollback the changes for entity A since the latest value for the A's status is no longer valid.


### Proposed Solutions:

We came up with two approaches directed at solving the above problems, which are described below.

### 1. **Queuing Operations**
This approach involves allowing the user to wrap the read-modify-write or additional custom ops into an action object/list and send it to the engine to be queued for execution. 

Pros:
- **Easy Failure Handling** - Since, the operation is abstracted to an action object and tracked in a better way, the rollback/failure handling mechanism is simple to implement.
- **Atomic `update_status` ops** - This design enables user to perform the read-modify-write in update_status as a single operation and hence guarantees atomicity in the `update_status` execution.
- **Synchronized Entity Updates** - The engine queues up the operations on an entity and hence guarantees synchronized updates to the entity.

Cons:
- **Design and Network Overhead** - This approach involved major updates to the design and implementation within papiea, and patching custom ops through http requests would also increase the network overhead within the system.
- **Race Conditions** - This approach does not guarantees safety against race conditions, since the status value is not updated/available till the entire operations is completed.

### 2. **Hashing Based Updates**:
This approach involves generation a hash out of the existing status value (or subset of fields) which give us a functionality similar to the spec version. The hash value is used by papiea to verify the update status call originated from an operations with the most recent value for the entity status.

Pros:
- **Less Design Overhead** - This approach has very less design overhead and require slight implementation changes. Moreover, this approach can be implemented quickly and continually improved later on.
- **Race Condition Safety** - The hash value verification in papiea guarantees safety against the race condition problem discussed above, since it will reject any updates to the status if the hash does not matches against the current value thereby preventing any race conditions (similar to the spec version check). 

Cons:
- **Complicated Failure Handling** - The failure handling scenario presented above as a problem would required changes in this approach to be handled correctly. One of the idea is to chain the hash received from the update_status calls so that we can revert to the original state using the hash.  
- **Additional Consideration for End-user** - This approach adds an additional considerations for the user, since they have to ensure they get the hash for the entity status (api call/included in context) and pass it in the `update_status` call as an additional parameter, even when there's no apparent reason to do so.

### **Conclusion:**
The benefits of simpler implementation approach and less design overhead along with race conditions safety tips us in favor of going with the `Hashing Based Updates` solution. However, we will need to be careful with the failure handling mechanism for this approach to ensure we don't run into any inconsistent behavior issues in the future.

**Comment by nitesh-idnani1** [comment]
### Implementation Details for `Hashing-Based Updates` (In Progress):

### Engine Changes
**Database changes** - I want to push the hash compare logic as far down in the pipeline as possible where we can be sure about the truthfulness of the status value, so the ideal component to add it to would be the **database** (mongo). We can set a **metadata** field named **`metadata.status_hash`** and set it's value along with the status update/replace. The **compare and update** logic for status hash would also be part of the **database** module.

**Error handling** - **Error handling** (in case of mismatched hash value) can be handled either through the existing **`ConflictingEntityError`** which is used in the **spec compare logic** or extend a new database error type suggesting **outdated/stale** value for the **status**.

**Hash computation** - For hashing, we can use the **object-hash module** which supports hashing for map/json based objects and is currently **included** as part of Igor's **"Fix watchlist and differ"** PR.


### End-user Changes

The interface for **update_status** still remains the **same**, with only difference being in the **metadata** field for the entity which now includes a **`status-hash`** field as well. The **usage** will still also be the **same** as shown below

```
entity = entity_client.get({ entity_uuid, entity_kind })
status = { ... }
update_status(entity.metadata, status)
```

Additionally, we can add support for a **util module** which allows user to **verify** the **status** value themselves by **passing** the **entity's metadata** which has the `status-hash` field and the **status** to be verified.

Failure Handling/Revert Status:
I think the idea here was to use the status hash to handle failures, and chain them in case of multiple operations within the procedure/intent handler. We still need to nail this down and come up with something concrete to go ahead with the implementation.

@joshua-berry-ntnx @Emulebest @shlomi-nx
Let me know what you guys think about this, and I need some input on the failure handling part.

**Comment by joshua-berry-ntnx** [comment]
> Database changes - I want to push the hash compare logic as far down in the pipeline as possible where we can be sure about the truthfulness of the status value, so the ideal component to add it to would be the database (mongo). ...

Agree.

> Error handling - Error handling (in case of mismatched hash value) can be handled either through the existing ConflictingEntityError

Generally agree. Perhaps we can have two different sub-types of ConflictingEntityError for spec and status, specifically, and then the base-class error can be caught as a general "hey you have a conflict in here somewhere".

> The interface for update_status still remains the same, with only difference being in the metadata field for the entity which now includes a status-hash field as well. The usage will still also be the same as shown below

Agree. Let's also make update_status() return the updated entity (with the new status hash). That way multiple changes are convenient to write, e.g.:

```ts
let entity = await client.get(...);

doSomethingWith(entity);
entity = await ctx.update_status(entity.metadata, {foo: 42});
expect(entity.status.foo).toEqual(42);

doSomethingElseWith(entity);
entity = await ctx.update_status(entity.metadata, {bar: "gold"});
expect(entity.status.foo).toEqual(42);
expect(entity.status.bar).toEqual("gold");

andSoOn();
```

One other thing to consider for the future: If we are planning to require a `status_hash` for update_status(), we might want to also simplify the status API to make it more similar to updating spec (i.e. pass the whole status), and thus give ourselves a way to avoid the oddities we have with `null` right now. But that probably shouldn't be part of this ticket.

> Failure Handling/Revert Status:
> I think the idea here was to use the status hash to handle failures, and chain them in case of multiple operations within the procedure/intent handler. We still need to nail this down and come up with something concrete to go ahead with the implementation.

Yeah, the above example illustrates the chaining. For failure/conflict handling, if anything else modifies the entity in the meantime, the update_status call will throw. So presumably that whole block of code would be wrapped in a try/catch block and a loop, just like we do today for code that changes spec:

```ts
while (true) {
    try {
        // ...all the code from the example above...
        break;
    } catch (e) {
        if (e instanceof ConflictingEntityError) continue;
        throw e;
    }
}
```

This idiom is common enough we might even want to put a convenience function in the SDK. Doing it in a type-safe way for TypeScript (i.e. without using `any`), such that you can return something from the convenience function, might be a fun exercise. :)

**Comment by nitesh-idnani1** [comment]
> > Error handling - Error handling (in case of mismatched hash value) can be handled either through the existing ConflictingEntityError
> 
> Generally agree. Perhaps we can have two different sub-types of ConflictingEntityError for spec and status, specifically, and then the base-class error can be caught as a general "hey you have a conflict in here somewhere".
> 
Agreed.
> > The interface for update_status still remains the same, with only difference being in the metadata field for the entity which now includes a status-hash field as well. The usage will still also be the same as shown below
> 
> Agree. Let's also make update_status() return the updated entity (with the new status hash). That way multiple changes are convenient to write, e.g.:
> 
> ```ts
> let entity = await client.get(...);
> 
> doSomethingWith(entity);
> entity = await ctx.update_status(entity.metadata, {foo: 42});
> expect(entity.status.foo).toEqual(42);
> 
> doSomethingElseWith(entity);
> entity = await ctx.update_status(entity.metadata, {bar: "gold"});
> expect(entity.status.foo).toEqual(42);
> expect(entity.status.bar).toEqual("gold");
> 
> andSoOn();
> ```
> 
We need to discuss this, since the current impl returns intent watcher responsible for the diffs produced due to the status update. Let's figure out if we can replace the watcher with updated status.
> One other thing to consider for the future: If we are planning to require a `status_hash` for update_status(), we might want to also simplify the status API to make it more similar to updating spec (i.e. pass the whole status), and thus give ourselves a way to avoid the oddities we have with `null` right now. But that probably shouldn't be part of this ticket.
> 
Okay, I'll take a note of this. We can discuss it after this issue is fixed.
> > Failure Handling/Revert Status:
> > I think the idea here was to use the status hash to handle failures, and chain them in case of multiple operations within the procedure/intent handler. We still need to nail this down and come up with something concrete to go ahead with the implementation.
> 
> Yeah, the above example illustrates the chaining. For failure/conflict handling, if anything else modifies the entity in the meantime, the update_status call will throw. So presumably that whole block of code would be wrapped in a try/catch block and a loop, just like we do today for code that changes spec:
> 
> ```ts
> while (true) {
>     try {
>         // ...all the code from the example above...
>         break;
>     } catch (e) {
>         if (e instanceof ConflictingEntityError) continue;
>         throw e;
>     }
> }
> ```
> 
I still have few concerns, let's discuss those in the sync.
> This idiom is common enough we might even want to put a convenience function in the SDK. Doing it in a type-safe way for TypeScript (i.e. without using `any`), such that you can return something from the convenience function, might be a fun exercise. :)
